# Generated by Django 4.2.6 on 2023-10-16 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año_desde', models.IntegerField()),
                ('año_hasta', models.IntegerField()),
                ('factor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipo_siniestro', models.CharField(choices=[('accidente', 'Accidente de tránsito'), ('robo', 'Robo'), ('falla', 'Falla de fábrica')], default='accidente', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('año', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_siniestro', models.CharField(choices=[('accidente', 'Accidente de tránsito'), ('robo', 'Robo'), ('falla', 'Falla de fábrica')], default='accidente', max_length=50)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_cotizado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.vehiculo')),
            ],
        ),
    ]
