# Generated by Django 4.2.5 on 2023-10-11 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_proyecto_comentario_tarea_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='proyecto',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Proyecto',
        ),
    ]
