# Generated by Django 4.2.5 on 2023-10-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_cotizacion_factorcotizacion_vehiculo_delete_tarea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='valor_asegurado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor a asegurar'),
        ),
    ]
