# Generated by Django 4.2.5 on 2023-10-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_vehiculo_valor_asegurado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='valor_asegurado',
        ),
        migrations.AddField(
            model_name='factorcotizacion',
            name='tipo_siniestro',
            field=models.CharField(choices=[('accidente', 'Accidente de tránsito'), ('robo', 'Robo'), ('falla', 'Falla de fábrica')], default='accidente', max_length=50),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo_siniestro',
            field=models.CharField(choices=[('accidente', 'Accidente de tránsito'), ('robo', 'Robo'), ('falla', 'Falla de fábrica')], default='accidente', max_length=50),
        ),
    ]
